# Generated by Django 3.2.15 on 2022-08-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='person_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('mail_id', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('branch', models.CharField(max_length=250)),
                ('account_type', models.CharField(max_length=250)),
                ('debit', models.BooleanField(default=True)),
                ('credit', models.BooleanField(default=True)),
                ('checkbook', models.BooleanField(default=True)),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.district')),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=250)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.district')),
            ],
        ),
    ]
