# Generated by Django 3.2.15 on 2022-08-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_auto_20220824_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_info',
            name='checkbook',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person_info',
            name='credit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person_info',
            name='debit',
            field=models.BooleanField(default=True),
        ),
    ]
