# Generated by Django 3.2.15 on 2022-08-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_auto_20220824_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_info',
            name='checkbook',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person_info',
            name='credit',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person_info',
            name='debit',
            field=models.CharField(max_length=200),
        ),
    ]
